### ISSUE TITLE
Command exception on execution with WorldGameRule 

### ISSUE THREAD

**Issue by suerion** [DrexHD/WorldGameRules#2]
Hey, on Fabric 1.21.1 i had an error on execution an command from gamerule. The Gamerule work, but only the server log an Error

Latest log:
https://mclo.gs/yAz5bK3

```
[19:57:53 ERROR] [Server thread]: [Commands] Command exception: /gamerule doDaylightCycle
com.google.gson.JsonParseException: Don't know how to turn $.with[1].placeholders into a Component
        at knot/net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.notSureHowToDeserialize(ComponentSerializerImpl.java:337) ~[net_kyori_adventure-text-serialigson-4.17.0-4ba253172218bafd.jar:?]
        at knot/net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:221) ~[net_kyori_adventure-text-serialigson-4.17.0-4ba253172218bafd.jar:?]
        at knot/net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:77) ~[net_kyori_adventure-text-serialigson-4.17.0-4ba253172218bafd.jar:?]
        at knot/com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.Gson.fromJson(Gson.java:1186) ~[gson-2.10.1.jar:?]
        at knot/net.kyori.adventure.text.serializer.gson.TranslationArgumentSerializer.read(TranslationArgumentSerializer.java:64) ~[net_kyori_adventure-text-serialigson-4.17.0-4ba253172218bafd.jar:?]
        at knot/net.kyori.adventure.text.serializer.gson.TranslationArgumentSerializer.read(TranslationArgumentSerializer.java:34) ~[net_kyori_adventure-text-serialigson-4.17.0-4ba253172218bafd.jar:?]
        at knot/com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.Gson.fromJson(Gson.java:1186) ~[gson-2.10.1.jar:?]
        at knot/net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:149) ~[net_kyori_adventure-text-serialigson-4.17.0-4ba253172218bafd.jar:?]
        at knot/net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:77) ~[net_kyori_adventure-text-serialigson-4.17.0-4ba253172218bafd.jar:?]
        at knot/com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at knot/com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
        at knot/net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserializeFromTree(GsonComponentSerializerImpl.java:109) ~[net_kyori_adventure-text-serialigson-4.17.0-4ba253172218bafd.jar:?]
        at knot/net.kyori.adventure.platform.fabric.impl.NonWrappingComponentSerializer.deserialize(NonWrappingComponentSerializer.java:64) ~[adventure-platform-fabric-5.14.1-a6b7a70abf0eed26.jar:?]
        at knot/net.kyori.adventure.platform.fabric.impl.server.FabricServerAudiencesImpl.toAdventure(FabricServerAudiencesImpl.java:190) ~[adventure-platform-fabric-5.14.1-a6b7a70abf0eed26.jar:?]
        at knot/net.minecraft.server.dedicated.DedicatedServer.sendSystemMessage(DedicatedServer.java:1257) ~[?:?]
        at knot/net.minecraft.commands.CommandSourceStack.broadcastToAdmins(CommandSourceStack.java:325) ~[?:?]
        at knot/net.minecraft.commands.CommandSourceStack.sendSuccess(CommandSourceStack.java:309) ~[?:?]
        at knot/me.drex.world_gamerules.command.WorldGameRuleCommand.getRule(WorldGameRuleCommand.java:87) ~[WorldGameRules-1.2.0+1.21.1.jar:?]
        at knot/me.drex.world_gamerules.command.WorldGameRuleCommand$1.lambda$visit$2(WorldGameRuleCommand.java:50) ~[WorldGameRules-1.2.0+1.21.1.jar:?]
        at knot/com.mojang.brigadier.context.ContextChain.mixinextras$bridge$run$9(ContextChain.java) ~[brigadier-1.3.10.jar:?]
        at knot/com.mojang.brigadier.context.ContextChain.wrapOperation$ffc000$melius-commands$runConditionally(ContextChain.java:562) ~[brigadier-1.3.10.jar:?]
        at knot/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at knot/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29) ~[?:?]
        at knot/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[?:?]
        at knot/net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[?:?]
        at knot/net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8) ~[?:?]
        at knot/net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:107) ~[?:?]
        at knot/net.minecraft.commands.Commands.executeCommandInContext(Commands.java:379) ~[?:?]
        at knot/net.minecraft.commands.Commands.performCommand(Commands.java:309) ~[?:?]
        at knot/net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:1319) ~[?:?]
        at knot/net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$7(ServerGamePacketListenerImpl.java:1307) ~[?:?]
        at knot/net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
        at knot/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:162) ~[?:?]
        at knot/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at knot/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at knot/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:136) ~[?:?]
        at knot/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at knot/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:121) ~[?:?]
        at knot/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:814) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by DrexHD** [comment]
Sounds like an incompatibility of [message-api](https://github.com/DrexHD/message-api) and [adventure](https://github.com/KyoriPowered/adventure) lib. Can you try with `better-fabric-console` mod removed?

**Comment by suerion** [comment]
Hey, yes i will, give you the feedback after testung. :)

**Comment by DrexHD** [comment]
It is an incompatibility between the mentioned libs. Unless a more recent version of adventure lib fixes the issue the better fabric console mod can't fix this. Should be reported to the libs instead.

**Comment by DrexHD** [comment]
This has been fixed for Minecraft 1.21.4 (?) and 1.21.5 in the mod version 1.3.4!
